name: Claude Auto PR

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: write
  pull-requests: write
  workflows: write

jobs:
  auto_pr:
    name: Create PR via Claude
    runs-on: ubuntu-latest

    # Only run when someone explicitly asks Claude to create a PR
    if: contains(github.event.comment.body, '@Claude create PR')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Use the PR's base repo/branch context if invoked from a PR,
          # or default to the repository default branch on issues.
          repository: ${{ github.repository }}
          ref: ${{ github.event.issue.pull_request.head.ref || '' }}

      - name: Run Claude PR action
        uses: anthropics/claude-code-action@v2
        with:
          mode: pr
          github_token: ${{ secrets.GITHUB_TOKEN }}
          claude_api_key: ${{ secrets.CLAUDE_API_KEY }}
          # Optional tuning:
          pr_branch_prefix: "claude-fix/"
          pr_title: "Claude: proposed changes"
          pr_body: |
            This PR was generated by Claude in response to a request in **${{ github.event.issue.html_url }}**.

            **Prompt from comment:**
            > ${{ github.event.comment.body }}

            **Notes:**
            - Please review generated changes.
            - Safe to close if not desired.
          # You can guide Claude with a high-level instruction set:
          system_prompt: |
            You are an AI code assistant operating in PR creation mode.
            - Make minimal, well-scoped changes addressing the user's request.
            - Include helpful commit messages.
            - Respect repository structure and linting.
            - Avoid touching CI files unless explicitly asked.

      - name: Output summary
        run: echo "If Claude made changes, a new PR should now be open."
